name: midgard_repository
description: A Dart Repository which manages the THORChain Midgard API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  json_annotation: ^4.0.0
  http: ^0.13.0
dev_dependencies:
  coverage: ^0.14.1
  build_runner: ^1.10.0
  json_serializable: ^4.0.0
  mocktail: ^0.1.0
  test: ^1.16.4
